Repository Yoast/yoast-acf-analysis, pull requests merged in 2020-07, with the labels that each got.

#267 Set minimum Yoast SEO version to 14.6
  inc/dependencies/dependency-yoast-seo.php
  readme.txt
  tests/php/unit/Dependencies/yoast-seo-dependency-test.php
Labels: changelog: non-user-facing

#263 PHPCS: enable caching between runs
  .cache/.gitkeep
  .gitattributes
  .gitignore
  .phpcs.xml.dist
  .travis.yml
Labels: changelog: non-user-facing, yoast cs/qa

#264 Travis/Composer: switch over to parallel linting of PHP files
  .travis.yml
  composer.json
  composer.lock
Labels: changelog: non-user-facing, yoast cs/qa

#262 Detect ACF blocks in preview, regardless of display mode
  js/src/collect/collect-v5.js
  js/yoast-acf-analysis.js
Labels: changelog: bugfix, community-patch

#270 CS: order `use` statements alphabetically
  tests/php/unit/Configuration/configuration-test.php
  tests/php/unit/main-test.php
  tests/php/unit/registry-test.php
  tests/php/unit/requirements-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#269 Travis: change from "trusty" to "xenial"
  .travis.yml
Labels: changelog: non-user-facing, yoast cs/qa
