Repository Yoast/yoast-acf-analysis, pull requests merged in 2023-01, with the labels that each got.

#327 Composer: update YoastCS and dependencies
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#328 Improve README.md
  README.md
Labels: changelog: non-user-facing

#329 bugfix: content in acf-fields was not included in analyses.
  js/src/collect/collect-v5.js
Labels: changelog: bugfix
